### ISSUE TITLE
Linux: libunshield.h error -> install unshield

### ISSUE THREAD

**Issue by keiem** [Tatsh/re3-installer#1]
Hello, just for reference.

If you get this error:

main.c:13:10: fatale fout: libunshield.h: Bestand of map bestaat niet
   13 | #include <libunshield.h>
      |          ^~~~~~~~~~~~~~~
compilatie is beëindigd.
make: *** [Makefile:15: main.o] Fout 1

you should install unshield.  On Arch based system, it's pacamn -S unshield

**Comment by Tatsh** [comment]
I am planning to make this use CMake so this won't happen without telling the user.

**Comment by keiem** [comment]
Maybe also a good idea to echo that it finished without errors and the result can be found in ~/.local/share/re3
